#!/usr/bin/env python3
"""Generate a subject repo's README from its manifest and documents.

    python3 generate_readme.py <subject-dir> [--check]

The convention treats README.md as derived, not authored (§3.9): the outline is
already in the markdown headings, and a hand-written copy of it goes stale the
first time a step is renamed. `--check` fails instead of writing, so CI can
catch a README that no longer matches the content.
"""
import argparse
import sys
from pathlib import Path

from ws_parser import parse_subject

BANNER = "<!-- GENERATED by generate_readme.py. Do not edit by hand. -->"


def plural(count, word):
    """French plural: `1 étape`, `2 étapes`. Words needing more than an -s are
    spelled out at the call site."""
    return f"{count} {word}" + ("s" if count > 1 else "")


def render(subject):
    project = subject.manifest["project"]
    out = [f"# {project['name']}", "", BANNER, "", project.get("summary", ""), ""]

    runtime = subject.manifest.get("runtime") or {}
    if runtime.get("engine"):
        language = f" ({runtime['language']})" if runtime.get("language") else ""
        out += [f"Moteur : **{runtime['engine']}**{language}.", ""]

    out += ["## Parcours", ""]
    for doc in subject.documents:
        if not doc.exercises:
            continue
        out += [f"### {doc.title}", ""]
        for exercise in doc.exercises:
            count = len(exercise.hints)
            suffix = f" ({plural(count, 'indice')})" if count else ""
            out.append(f"- {exercise.title}{suffix}")
        out.append("")

    hints = sum(len(e.hints) for e in subject.exercises)
    parts = [f"**{plural(len(subject.exercises), 'étape')}**"]
    if subject.quizzes:
        parts.append(f"{len(subject.quizzes)} quiz")      # invariable
    if hints:
        parts.append(plural(hints, "indice"))
    if subject.assets:
        parts.append(plural(len(subject.assets), "image"))
    out += [", ".join(parts) + ".", ""]
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("subject_dir", nargs="?", default=".")
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if README.md is missing or stale")
    args = ap.parse_args()

    content = render(parse_subject(args.subject_dir))
    readme = Path(args.subject_dir) / "README.md"

    if args.check:
        current = readme.read_text() if readme.exists() else ""
        if current != content:
            sys.exit(f"{readme} is out of date — run: python3 generate_readme.py "
                     f"{args.subject_dir}")
        print(f"ok {readme} is up to date")
        return

    readme.write_text(content)
    print(f"wrote {readme}")


if __name__ == "__main__":
    main()
